apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vault-test-1
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: secret-vault-test-1
  data:
    - secretKey: pass
      remoteRef:
        key: test1
        property: pass
